### ISSUE TITLE
Java free version

### ISSUE THREAD

**Issue by ghost** [tomighty/tomighty#107]
I really like tomighty.

It would be wonderful if Java wasn't required for it to run (on windows).

~~At the moment Java is deemed quite a substantial security risk which quite a few users are not willing to take. ~~ I guess this only applies to the browser plugins.
Then again, People need to install Java. On my machines Java always seems to be in some sort of perpetual update cycle which fails and is annoying. 

Is it feasible to rewrite tomighty without java?

**Comment by ariel-rios-movile** [comment]
@GoodKey I would like to hear more about that "security risk" that you are talking about... what do you mean?

**Comment by TheDarkTrumpet** [comment]
I think what he means is something like this chart:

http://www.cvedetails.com/product/1526/SUN-JRE.html?vendor_id=5
http://www.cvedetails.com/product/19117/Oracle-JRE.html?vendor_id=93

http://www.reuters.com/article/2013/01/14/us-java-oracle-security-idUSBRE90D10P20130114

While a lot of the java issues are integrated with the browser, and thus
applets/java/flash should be "click to enable" or flat out disabled all
together, there's a perception about Java being insecure given the # of
security issues that come up with it.

Krebs writes a lot about java too - http://krebsonsecurity.com/tag/java/

-David

On Wed, Jan 28, 2015 at 5:23 PM, ariel-rios-movile <notifications@github.com

**Comment by ghost** [comment]
I must admit it perhaps was stupid to open an issue on this. I think TheDarkTrumpet explained where my fear came from. 

Still Java runtime can be quite troublesome, won't you agree? (e.g. perpetual update cycle problems)

**Comment by ccidral** [comment]
Hi @GoodKey.  A few months ago I started rewriting Tomighty in Qt5/C++, which means we're moving away from the Java platform. The main reason is AWT's tray icon, which plays a key role in Tomighty, behaves inconsistently across platforms.  The new source code can be found in the `develop` branch.  The development has been halted, though, because I'm unable to work on the project at the moment, but I expect to be able to resume working on it soon, probably in April.

Regarding Java's security concerns, I consider Java as (in)secure as any other decent piece of software.  Just look at the Linux ecosystem, or even the Linux kernel, it gets updated with fixes almost everyday, but still they are great pieces of software. That's just in the nature of software development. But that's my 2 cents though.
