### ISSUE TITLE
Maximized windows are ugly

### ISSUE THREAD

**Issue by cwarden** [tomighty/tomighty#49]
The timer and break windows could look prettier when maximized:

![timer](https://raw.github.com/gist/5acd2d33264c64bc6de5/75c97c322e2dbb6a4d3103ca4d4470a75ed6690a/2011-08-25-133947_1598x898_scrot.png)

![break](https://raw.github.com/gist/5acd2d33264c64bc6de5/471e42c9b9072cec72cfc23703ff88b6c8ea8031/2011-08-25-134527_1598x898_scrot.png)

**Comment by ccidral** [comment]
Wow, how did you do that? This window is not supposed to be maximized.

**Comment by cwarden** [comment]
I made my window manager, xmonad, tile the floating window.  Admittedly an unusual use case, but I didn't want anything else on that screen, and tiling the tomighty window allowed me to hide the status bar/dock.

**Comment by cwarden** [comment]
fwiw, it looks like the Gradient theme has the largest background images so it looks best.

**Comment by ccidral** [comment]
That is because Tomighty caches the background into an image file after it paints it.  Probably you had the window maximized then switched themes and the new background (which was not cached at this point) was painted on a larger area. I think it's an easy change if you want to make Tomighty distinguish cached backgrounds by size.
